/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrajetoriaRouteImport } from './routes/trajetoria'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuemSouRouteImport } from './routes/quem-sou'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as ProducaoLiterariaRouteImport } from './routes/producao-literaria'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as DossieRouteImport } from './routes/dossie'
import { Route as ContribuicaoRouteImport } from './routes/contribuicao'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CompetenciasRouteImport } from './routes/competencias'
import { Route as CertificadosRouteImport } from './routes/certificados'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosSlugRouteImport } from './routes/projetos.$slug'

const TrajetoriaRoute = TrajetoriaRouteImport.update({
  id: '/trajetoria',
  path: '/trajetoria',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSouRoute = QuemSouRouteImport.update({
  id: '/quem-sou',
  path: '/quem-sou',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducaoLiterariaRoute = ProducaoLiterariaRouteImport.update({
  id: '/producao-literaria',
  path: '/producao-literaria',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const DossieRoute = DossieRouteImport.update({
  id: '/dossie',
  path: '/dossie',
  getParentRoute: () => rootRouteImport,
} as any)
const ContribuicaoRoute = ContribuicaoRouteImport.update({
  id: '/contribuicao',
  path: '/contribuicao',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetenciasRoute = CompetenciasRouteImport.update({
  id: '/competencias',
  path: '/competencias',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificadosRoute = CertificadosRouteImport.update({
  id: '/certificados',
  path: '/certificados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosSlugRoute = ProjetosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjetosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificados': typeof CertificadosRoute
  '/competencias': typeof CompetenciasRoute
  '/contato': typeof ContatoRoute
  '/contribuicao': typeof ContribuicaoRoute
  '/dossie': typeof DossieRoute
  '/galeria': typeof GaleriaRoute
  '/producao-literaria': typeof ProducaoLiterariaRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/quem-sou': typeof QuemSouRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trajetoria': typeof TrajetoriaRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificados': typeof CertificadosRoute
  '/competencias': typeof CompetenciasRoute
  '/contato': typeof ContatoRoute
  '/contribuicao': typeof ContribuicaoRoute
  '/dossie': typeof DossieRoute
  '/galeria': typeof GaleriaRoute
  '/producao-literaria': typeof ProducaoLiterariaRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/quem-sou': typeof QuemSouRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trajetoria': typeof TrajetoriaRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificados': typeof CertificadosRoute
  '/competencias': typeof CompetenciasRoute
  '/contato': typeof ContatoRoute
  '/contribuicao': typeof ContribuicaoRoute
  '/dossie': typeof DossieRoute
  '/galeria': typeof GaleriaRoute
  '/producao-literaria': typeof ProducaoLiterariaRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/quem-sou': typeof QuemSouRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trajetoria': typeof TrajetoriaRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certificados'
    | '/competencias'
    | '/contato'
    | '/contribuicao'
    | '/dossie'
    | '/galeria'
    | '/producao-literaria'
    | '/projetos'
    | '/quem-sou'
    | '/sitemap.xml'
    | '/trajetoria'
    | '/projetos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificados'
    | '/competencias'
    | '/contato'
    | '/contribuicao'
    | '/dossie'
    | '/galeria'
    | '/producao-literaria'
    | '/projetos'
    | '/quem-sou'
    | '/sitemap.xml'
    | '/trajetoria'
    | '/projetos/$slug'
  id:
    | '__root__'
    | '/'
    | '/certificados'
    | '/competencias'
    | '/contato'
    | '/contribuicao'
    | '/dossie'
    | '/galeria'
    | '/producao-literaria'
    | '/projetos'
    | '/quem-sou'
    | '/sitemap.xml'
    | '/trajetoria'
    | '/projetos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificadosRoute: typeof CertificadosRoute
  CompetenciasRoute: typeof CompetenciasRoute
  ContatoRoute: typeof ContatoRoute
  ContribuicaoRoute: typeof ContribuicaoRoute
  DossieRoute: typeof DossieRoute
  GaleriaRoute: typeof GaleriaRoute
  ProducaoLiterariaRoute: typeof ProducaoLiterariaRoute
  ProjetosRoute: typeof ProjetosRouteWithChildren
  QuemSouRoute: typeof QuemSouRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrajetoriaRoute: typeof TrajetoriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trajetoria': {
      id: '/trajetoria'
      path: '/trajetoria'
      fullPath: '/trajetoria'
      preLoaderRoute: typeof TrajetoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-sou': {
      id: '/quem-sou'
      path: '/quem-sou'
      fullPath: '/quem-sou'
      preLoaderRoute: typeof QuemSouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producao-literaria': {
      id: '/producao-literaria'
      path: '/producao-literaria'
      fullPath: '/producao-literaria'
      preLoaderRoute: typeof ProducaoLiterariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossie': {
      id: '/dossie'
      path: '/dossie'
      fullPath: '/dossie'
      preLoaderRoute: typeof DossieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribuicao': {
      id: '/contribuicao'
      path: '/contribuicao'
      fullPath: '/contribuicao'
      preLoaderRoute: typeof ContribuicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competencias': {
      id: '/competencias'
      path: '/competencias'
      fullPath: '/competencias'
      preLoaderRoute: typeof CompetenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificados': {
      id: '/certificados'
      path: '/certificados'
      fullPath: '/certificados'
      preLoaderRoute: typeof CertificadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$slug': {
      id: '/projetos/$slug'
      path: '/$slug'
      fullPath: '/projetos/$slug'
      preLoaderRoute: typeof ProjetosSlugRouteImport
      parentRoute: typeof ProjetosRoute
    }
  }
}

interface ProjetosRouteChildren {
  ProjetosSlugRoute: typeof ProjetosSlugRoute
}

const ProjetosRouteChildren: ProjetosRouteChildren = {
  ProjetosSlugRoute: ProjetosSlugRoute,
}

const ProjetosRouteWithChildren = ProjetosRoute._addFileChildren(
  ProjetosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificadosRoute: CertificadosRoute,
  CompetenciasRoute: CompetenciasRoute,
  ContatoRoute: ContatoRoute,
  ContribuicaoRoute: ContribuicaoRoute,
  DossieRoute: DossieRoute,
  GaleriaRoute: GaleriaRoute,
  ProducaoLiterariaRoute: ProducaoLiterariaRoute,
  ProjetosRoute: ProjetosRouteWithChildren,
  QuemSouRoute: QuemSouRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrajetoriaRoute: TrajetoriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
